server {
   listen 80;
   listen [::]:80;
   server_name fe.universalmct.ai;


   # Redirect all HTTP requests to HTTPS
   return 301 https://$server_name$request_uri;
}


server {
   listen 443 ssl;  # Enable SSL and HTTP/2 on this line
   listen [::]:443 ssl;  # Same for IPv6
   server_name fe.universalmct.ai;


   # SSL Configuration
   ssl_certificate /etc/nginx/ssl/fe.universalmct.ai.pem;  # Path to your SSL certificate
   ssl_certificate_key /etc/nginx/ssl/fe.universalmct.aikey.pem;  # Path to your SSL key
   ssl_protocols TLSv1.2 TLSv1.3;
   ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256';
   ssl_prefer_server_ciphers on;
   ssl_session_cache shared:SSL:10m;
   ssl_session_timeout 10m;


   # Improve SSL performance
   ssl_session_tickets off;


   # Security headers
   add_header Strict-Transport-Security "max-age=31536000" always;
   add_header X-Frame-Options DENY;
   add_header X-Content-Type-Options nosniff;


   # Proxy settings
   location / {
       proxy_pass http://localhost:3000;
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection 'upgrade';
       proxy_set_header Host $host;
       proxy_cache_bypass $http_upgrade;
   }



}
